import Head from "next/head";
import Layout from "components/Layout";

const Index = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout />
    </>
  );
};

export default Index;
