import Head from "next/head";
import Layout from "../components/Layout.js";
// import favicon from "../public/favicon.ico";

const Index = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        {/* <link rel="icon" href={favicon} /> */}
      </Head>
      <Layout />
    </>
  );
};

export default Index;
